#Build stage
FROM node:20-alpine AS development

WORKDIR /usr/src/app

COPY package*.json .
 
RUN npm install

COPY . .

RUN npm run build

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

#Production stage
FROM node:20-alpine AS production

WORKDIR /usr/src/app

COPY package*.json .

RUN npm ci --only=production

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/index.js"]